version: '3'
services:
  web:
    image: dradis/dradis-ce:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: cYNo3sAcyqJea0AxBP6A
